### ISSUE TITLE
apt-preference php@sury_php throws error

### ISSUE THREAD

**Issue by tristanbes** [manala/ansible-role-apt#23]
Hey,

Using ansible 2.2.1.0
```
manala_apt_preferences:
  - php@sury_php

manala_php_version: 7.1
```

runnning the **manala.apt** playbook result in:

```
TASK [manala.apt : preferences > Templates] ************************************
task path: /Users/xxxx/workspace/System/roles/manala.apt/tasks/preferences.yml:3
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 90, in run
    items = self._get_loop_items()
  File "/usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 205, in _get_loop_items
    items = mylookup.run(terms=loop_terms, variables=self._job_vars, wantlist=True)
  File "/Users/xxxx/workspace/System/roles/manala.apt/lookup_plugins/manala_apt_preferences.py", line 40, in run
    ).split(':')[0]
KeyError: u'sury_php'

fatal: [xxxxxx.com]: FAILED! => {
    "failed": true,
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
```

commenting the `manala_apt_preferences` key solves the issue

**Comment by tristanbes** [comment]
Will be fixed in : https://github.com/manala/ansible-role-apt/pull/22
